### ISSUE TITLE
Live site produces "Dangerous" warning in Google Chrome

### ISSUE THREAD

**Issue by DelphiCoder** [WebDevSimplified/twitter-clone#1]
I'm not sure if you are aware of this. But your live site for your twitter-clone project generates a red "Deceptive site ahead" warning inside Chrome.  I don't know why though or what you can do about it.  But I thought you should know.

![warning](https://user-images.githubusercontent.com/11362009/234073911-0134565d-39ce-452b-87a6-6c319ca800bc.jpg)

**Comment by DelphiCoder** [comment]
Stranger still, Microsoft Edge does this:

![warning_edge](https://user-images.githubusercontent.com/11362009/234075023-6a0c1498-cc07-4c2d-9fa9-c519d7283b7b.jpg)

**Comment by WebDevSimplified** [comment]
The Chrome issue is (I think) because I used `twitter-clone` in the title and they are worried I am trying to mislead people into thinking my site is Twitter.

The Edge issue is because I removed the site from Vercel. So it no longer exists. I have removed the URL from the repo so it hopefully won't cause any more issues.
